CREATE DATABASE MusicProjectDb
GO
USE MusicProjectDb
GO
CREATE TABLE Favorites(
Id INT PRIMARY KEY IDENTITY(1,1),
Album NVARCHAR(60),
Artist NVARCHAR(50),
Track NVARCHAR(50),
AlbumId NVARCHAR(50),
ArtistId NVARCHAR(50),
TrackId NVARCHAR(50),
UserId INT FOREIGN KEY REFERENCES Favorites(Id));

