CREATE DATABASE MusicProjectDb
GO
USE MusicProjectDb
GO
CREATE TABLE Favorites(
Id INT PRIMARY KEY IDENTITY(1,1)
);
CREATE TABLE UserFavorites(
Id INT PRIMARY KEY IDENTITY(1,1),
Album NVARCHAR(60),
Artist NVARCHAR(50),
Track NVARCHAR(50),
IdNetUsers INT FOREIGN KEY REFERENCES UserFavorites(Id)
);